# This is a basic workflow to help you get started with Actions

name: gh-pages-pr
concurrency: preview-${{ github.ref }}
# Controls when the action will run. 
on:
  pull_request_target:                  # pull request build
    branches:
      - '*'
    types:
      - opened
      - synchronize
      - reopened
      - labeled                         # requires the `build-docs` label

  workflow_dispatch:                    # manual trigger
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          clean: true

      # Runs a single command using the runners shell
      - name: Build 
        run: |-
          pip install -r requirements.txt && sphinx-build -b html -d html/doctrees . html/
          touch html/.nojekyll

      - name: Deploy PR to GitHub Pages
        if: success()
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
          source-dir: ./html/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: rossjrw/pr-preview-action@v1
        if: github.event.action == "closed" && !github.event.pull_request.merged
        with:
          source-dir: ./html/
          action: remove
      
  
